name: databricksJobSqlProject
description: ''
version: 0.0.1
author: chirag@prophecy.io
language: sql
buildSystem: ''
buildSystemDetails: null
pipelines: {}
datasets: {}
templates: {}
jobs:
  jobs/DataJob:
    name: DataJob
    description: ''
    fabricUID: 3068
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: 0 0/4 * * * ? *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2024-09-11 04:56:40'
    author: chirag@prophecy.io
    models: []
    sqlProjects:
    - '14730'
gemContainer:
  languageVersion: ''
  gemLibsVersion: ''
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-09-11 04:56:09'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels:
  .prophecy/metadata/sqlmodels/temp:
    name: temp
    schema:
      entityType: ''
      providerType: Databricks
      fields:
      - name: id
        dataType:
          type: Integer
    description: null
    author: chirag@prophecy.io
    files:
    - models/temp.sql
    - .prophecy/ide/models/temp.json
    - models/schema.yml
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-09-12 09:19:03'
sqlSnapshots: {}
sqlTests:
  .prophecy/metadata/sqltests/is_even:
    name: is_even
    description: null
    author: chirag@prophecy.io
    files:
    - tests/generic/is_even.sql
    testType: GenericDataTest
    createdAt: '2024-09-20 10:09:02'
sqlMacros:
  .prophecy/metadata/sqlmacros/generate_schema_name:
    name: generate_schema_name
    macroType: expression
    description: null
    author: chirag@prophecy.io
    files:
    - macros/generate_schema_name.sql
    - .prophecy/ide/macros/generate_schema_name.json
    createdAt: '2024-09-11 04:56:11'
sqlSeeds:
  .prophecy/metadata/sqlseeds/abc:
    name: abc
    schema:
      entityType: ''
      providerType: Databricks
      fields:
      - name: id
        dataType:
          type: Integer
    description: null
    author: chirag@prophecy.io
    files:
    - seeds/abc.csv
    createdAt: '2024-09-11 04:56:51'
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline:
  name: sqlPipeline
  description: null
  author: chirag@prophecy.io
  createdAt: '2024-09-11 04:56:09'
dependencies: []
projectDependencies: {}
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
