name: GitProject
description: ''
version: 0.0.1
author: chirag@prophecy.io
language: sql
buildSystem: ''
buildSystemDetails: null
pipelines: {}
datasets: {}
templates: {}
jobs:
  jobs/GitAirflowJob:
    name: GitAirflowJob
    description: ''
    fabricUID: 8
    scheduler:
      Composer: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: 0/10 * * * *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2024-09-06 05:12:26'
    author: chirag@prophecy.io
    models: []
    sqlProjects:
    - '44'
gemContainer:
  languageVersion: ''
  gemLibsVersion: ''
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-09-06 04:41:30'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels:
  .prophecy/metadata/sqlmodels/OrderId:
    name: OrderId
    schema:
      entityType: ''
      providerType: Snowflake
      fields:
      - name: ID
        dataType:
          type: Number
    description: null
    author: chirag@prophecy.io
    files:
    - models/OrderId.sql
    - .prophecy/ide/models/OrderId.json
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-09-06 04:43:41'
sqlSnapshots: {}
sqlTests: {}
sqlMacros:
  .prophecy/metadata/sqlmacros/generate_schema_name:
    name: generate_schema_name
    macroType: expression
    description: null
    author: chirag@prophecy.io
    files:
    - macros/generate_schema_name.sql
    - .prophecy/ide/macros/generate_schema_name.json
    createdAt: '2024-09-06 04:41:37'
sqlSeeds:
  .prophecy/metadata/sqlseeds/ids:
    name: ids
    schema:
      entityType: ''
      providerType: Snowflake
      fields:
      - name: id
        dataType:
          type: Number
    description: null
    author: chirag@prophecy.io
    files:
    - seeds/ids.csv
    createdAt: '2024-09-06 04:42:58'
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline:
  name: sqlPipeline
  description: null
  author: chirag@prophecy.io
  createdAt: '2024-09-06 04:41:30'
dependencies: []
projectDependencies: {}
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
