version: 2

models:
  - name: OrderId
    tests:
      - is_even:
          config: { }
          column_name: "id"
          accepted_values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
    columns:
      - name: id
        tests:
          - unique
          - not_null