---
version: 2
models:
- name: "OrderId"
  columns:
  - name: "ID"
    tests:
    - unique:
        config: {}
    - is_even:
        config: {}
        accepted_values: "1"
    dataType:
      type: "Number"
  tests: []
